import type { ApplicationState } from '@lj/domain';

/**
 * Whether this application has a document pack to look at, and where it is.
 *
 * Phase 6 shipped the pack at `/apply/:id/documents` and nothing linked to it.
 * A borrower whose application had reached `docs_pending` opened it from their
 * list, landed on the four-step form at `furthest_step`, and was given no sign
 * that documents were now the thing being waited on. The feature was built,
 * tested, deployed and unreachable (issue #54).
 *
 * The decision is a plain function rather than an expression in the shell's
 * template for two reasons: it is testable here and not there (issue #33 -- an
 * apps/web unit test cannot render a component that uses @lj/ui), and it is a
 * statement about the machine rather than about layout.
 *
 * This file deliberately knows nothing about what the pack CONTAINS. Whether a
 * document is outstanding, and how many, is `evaluateCompleteness` in
 * @lj/rules, read by `features/documents/`; re-deriving any of it here would be
 * a second definition of what a pack needs (CLAUDE.md section 9), and
 * `features/` scopes may not import each other in any case.
 */

/**
 * The states in which slots exist.
 *
 * Slots are generated by the `create_document_slots` effect on `request_docs`,
 * so nothing before `docs_pending` has a pack. Everything after it does, and
 * keeps it: the pack does not stop existing because the file moved on, and a
 * borrower looking at an approved application can still see what they sent.
 *
 * `withdrawn` is deliberately absent, and it is the only interesting entry.
 * `withdraw` leaves four states -- draft, submitted, docs_pending and
 * needs_borrower_action -- and only two of those have a pack, so the state
 * alone cannot answer. Silence is the reading that cannot mislead: the
 * application is terminal and nobody is being asked for anything. Offering a
 * link that lands on an empty checklist would teach the applicant that links
 * here are noise, which costs more than the link is worth.
 *
 * Written as a full map over the union rather than a list, so a state added to
 * the machine and forgotten here fails `tsc` instead of rendering as a missing
 * link nobody notices -- the same reason the label maps in @lj/domain are
 * written that way.
 */
const PACK_EXISTS: { readonly [K in ApplicationState]: boolean } = {
  draft: false,
  submitted: false,
  docs_pending: true,
  under_review: true,
  needs_borrower_action: true,
  approved: true,
  declined: true,
  funded: true,
  withdrawn: false,
};

export function hasDocumentPack(state: ApplicationState): boolean {
  return PACK_EXISTS[state];
}

/** The pack's route, as a router link array. */
export function documentPackPath(applicationId: string): readonly string[] {
  return ['/apply', applicationId, 'documents'];
}
