import { APPLICATION_STATES, type ApplicationState } from '@lj/domain';

import { documentPackPath, hasDocumentPack } from './documents-entry.ts';

/**
 * When a borrower is shown the way into their document pack.
 *
 * The defect this answers is that they never were: phase 6 shipped the pack and
 * nothing linked to it, so an application sitting at `docs_pending` opened onto
 * the four-step form with no sign that documents were now what was wanted.
 */
describe('hasDocumentPack', () => {
  // Slots are generated by the `create_document_slots` effect on
  // `request_docs`, so before that transition there is nothing to look at and
  // a link would teach the applicant that links here are noise.
  it('is silent while the application is still being written', () => {
    expect(hasDocumentPack('draft')).toBe(false);
    expect(hasDocumentPack('submitted')).toBe(false);
  });

  it('offers the pack from the moment the lender asks for documents', () => {
    expect(hasDocumentPack('docs_pending')).toBe(true);
  });

  // The pack does not stop existing because the file moved on. A borrower
  // looking at an approved application can still see what they sent, and a
  // lender reviewing one certainly can.
  it('keeps offering it once the file has moved past collection', () => {
    for (const state of ['under_review', 'needs_borrower_action', 'approved', 'funded', 'declined'] as const) {
      expect(hasDocumentPack(state)).toBe(true);
    }
  });

  // `withdraw` leaves four different states, only two of which have a pack, so
  // the state alone cannot say. Silence is the answer that cannot mislead: a
  // withdrawn application is terminal and nobody is being asked for anything.
  it('says nothing about a withdrawn application, because the state cannot', () => {
    expect(hasDocumentPack('withdrawn')).toBe(false);
  });

  // A state added to the machine and forgotten here would render as a missing
  // link that nobody notices. Every state is decided, one way or the other.
  it('has an answer for every state the machine declares', () => {
    for (const state of APPLICATION_STATES) {
      expect(typeof hasDocumentPack(state as ApplicationState)).toBe('boolean');
    }
  });
});

describe('documentPackPath', () => {
  it('addresses the pack under the application it belongs to', () => {
    expect(documentPackPath('00000000-0000-4000-8000-0000000000d1')).toEqual([
      '/apply',
      '00000000-0000-4000-8000-0000000000d1',
      'documents',
    ]);
  });
});
